vich_uploader:
    db_driver: orm

    mappings:
        item_image:
            uri_prefix:         '%app.path.item_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.item_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer